services:
  frontend:
    container_name: "kayman-frontend"
    depends_on:
      - "backend"
    image: "tomy0000000/kayman-frontend"
    restart: "always"

  backend:
    container_name: "kayman-backend"
    depends_on:
      - "db"
    env_file:
      - "instance/.env"
    image: "tomy0000000/kayman-backend"
    restart: "always"
    volumes:
      - "./instance:/usr/src/kayman/instance"

  db:
    container_name: "kayman-db"
    env_file:
      - "instance/.env"
    image: "postgres:18"
    restart: "always"
    volumes:
      - "data:/var/lib/postgresql/data"

volumes:
  data:
