services:
  frontend:
    build:
      dockerfile: "frontend/Dockerfile"
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: "backend/Dockerfile"
    command: "--reload --log-level trace"
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/usr/src/kayman"

  db:
    ports:
      - "5432:5432"
