[tools]
hadolint = "2.14.0"
node = "26.3.1"
pnpm = "11.8.0"
python = "3.12"
uv = "0.10.10"

[task_config]
includes = ["scripts", "backend/scripts", "frontend/scripts"]

[tasks.start]
description = "Start all dev servers"
depends = ["start:backend", "start:frontend"]

[tasks."setup:db"]
description = "Setup empty database for local development, DO NOT use this in production, data will NOT persist!"
run = ["mise run start:db", "mise run db:upgrade"]
