"""add transaction posted_at

Revision ID: cc62725c07b7
Revises: be372c32e055
Create Date: 2026-06-10 02:28:09.619310

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cc62725c07b7"
down_revision = "be372c32e055"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction", sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "posted_at")
    # ### end Alembic commands ###
