"""add event cleared_at

Revision ID: 0039
Revises: 0038
Create Date: 2026-07-19 03:48:43.469123

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event", sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "cleared_at")
    # ### end Alembic commands ###
