"""add transaction tag and link

Revision ID: 0040
Revises: 0039
Create Date: 2026-07-19 16:24:55.340209

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "0040"
down_revision = "0039"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_tag",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="transaction_tag_name_key"),
    )
    op.create_table(
        "transaction_tag_link",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("transaction_tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transaction.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["transaction_tag_id"], ["transaction_tag.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("transaction_id", "transaction_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_tag_link")
    op.drop_table("transaction_tag")
    # ### end Alembic commands ###
