"""add category index

Revision ID: 0042
Revises: 0041
Create Date: 2026-08-09 00:19:10.457854

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0042'
down_revision = '0041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category",
        sa.Column(
            "index",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'index')
    # ### end Alembic commands ###
