"""add account index

Revision ID: 0046
Revises: 0045
Create Date: 2026-09-06 14:13:54.247217

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0046'
down_revision = '0045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column(
            "index",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'index')
    # ### end Alembic commands ###
