"""add statement period balance and due date

Revision ID: 0047
Revises: 0046
Create Date: 2026-09-07 23:01:29.710469

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0047'
down_revision = '0046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement', sa.Column('period_start_on', sa.Date(), nullable=False))
    op.add_column('statement', sa.Column('period_end_on', sa.Date(), nullable=False))
    op.add_column('statement', sa.Column('balance', sa.Numeric(), nullable=False))
    op.add_column('statement', sa.Column('due_on', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statement', 'due_on')
    op.drop_column('statement', 'balance')
    op.drop_column('statement', 'period_end_on')
    op.drop_column('statement', 'period_start_on')
    # ### end Alembic commands ###
