"""nullable transaction payment_id and index

Revision ID: f4f177b1ada3
Revises: cc62725c07b7
Create Date: 2026-06-13 23:08:15.683880

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f4f177b1ada3"
down_revision = "cc62725c07b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "payment_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("transaction", "index", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transaction", "index", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "transaction", "payment_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
